### ISSUE TITLE
How to close a ticket?

### ISSUE THREAD

**Issue by frenzymadness** [mcurlej/joft#10]
How can I leverage this tool to close all tickets a query finds with a meaningful comment and specific resolution?

**Comment by frenzymadness** [comment]
To add a comment, it seems to be possible to use a dedicated endpoint or use the update functionality to achieve the same: https://developer.atlassian.com/server/jira/platform/jira-rest-api-example-add-comment-8946422/

**Comment by frenzymadness** [comment]
And the closing might be possible as well and also together with the comment:

```
{
        "update": {
            "comment": [
                {
                    "add": {
                        "body": "Resolved via automated process."
                    }
                }
            ]
        },
        "transition": {
            "id": "761"
        },
        "fields": {
            "resolution": {
                "name": "Done"
            }
        }
    }
```
I know the ids for transition and the resolution but it might be more readable to use their names. I have to test it first.

**Comment by frenzymadness** [comment]
But I'm not sure this is gonna work here:
```
update:
  comment:
    - add:
        body: "Resolved via automated process."
transition:
  name: "Closed"
fields:
  resolution:
    name: "Done"
```
Do you know if we need to create a new action for this?
