### ISSUE TITLE
update-ticket action does not support the update parameter of jira.resources.Issue.update()

### ISSUE THREAD

**Issue by neverpanic** [mcurlej/joft#47]
I'd like to write a template that adds a label to all issues matching a query. According to https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#editing-an-issue-examples, the way to do this would be to call `Issue.update()` with the `update` parameter set to

```yaml
update:
  components:
    - add:
        name: "Engine"
    - remove:
        name: "Trans/A"
```

See the API docs for `Issue.update()`: https://jira.readthedocs.io/api.html#jira.resources.Issue.update

joft seems to currently only support setting the fields parameter: https://github.com/mcurlej/joft/blob/main/joft/actions.py#L53.
